name: 'Hello World'
description: 'Greet someone and record the time'
inputs:
  project:  # id of input
    description: 'project name'
    required: true
runs:
  using: 'node16'
  main: 'dist/index.js'